### ISSUE TITLE
Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by FernandoFranco** [mrodal/vue-inheritance-loader#7] opened 2019-10-30 14:31 UTC
I get "Unable to read property 'options' of undefined" src / index.js on line 26.
this._compiler for some reason is not present, but not enough to tell why

Apparently a simple condition solves, but I don't know what consequences it could bring.
`let aliases = (this._compiler && this._compiler.options.resolve.alias) || null;`

**Comment by mrodal** [comment] 2019-10-30 14:37
which webpack version are you using?

**Comment by FernandoFranco** [comment] 2019-10-31 14:26
Sorry, at line 26, I changed it back to:
`let aliases = (this._compiler && this._compiler.options.resolve.alias) || {}; `

So I get no errors consuming `aliases` when trying to retrieve ['__fromJest'].

**Comment by mrodal** [comment] 2019-11-02 23:43
Hmm.. its weird.. could you upload a minimal example showing this error?

**Comment by FernandoFranco** [comment] 2019-11-04 12:16
Currently the project containing the loader is commercial, and I don't have permissions to expose the code.
But I will try to create another project that simulates the same problem as soon as possible.

**Comment by FernandoFranco** [comment] 2019-11-13 11:40
Sorry for the delay.
[vue-inheritance-loader-issue](https://github.com/FernandoFranco/vue-inheritance-loader-issue).

I use yarn.
To get the error, run: `yarn build --mode production`

**Comment by jtyuan** [comment] 2019-11-15 20:37
Same issue happened to me for versions `>= 0.1.8`

**Comment by mrodal** [comment] 2019-11-17 13:44
@FernandoFranco Sorry, I can't reproduce the issue.
I downloaded your repo, ran `yarn` and then `yarn build --mode production` and it built without issues :\

If you do these same steps you get the error?

**Comment by FernandoFranco** [comment] 2019-11-19 11:33
Curious, when I climbed, this sequence of commands threw the error.
But I did the same today to check and did not give ...

**Comment by mrodal** [comment] 2019-11-19 13:04
Ok, maybe it was the older version as @jtyuan said, Im closing for now, if it happens again please comment and I'll reopen

**Closed by mrodal** 2019-11-19 13:04 UTC

**Comment by MatthewBooth** [comment] 2020-02-13 14:41
I'm getting this error today when doing a production build. Seems to be the same location and when run via a CI pipeline. A dev build is working fine.

**Comment by MatthewBooth** [comment] 2020-02-13 15:01
I'll start a new issue. I think this is fixed by someone else. I'll know shortly
